import smtplib
import logging
import calendar
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email                import encoders
from typing               import List, Tuple

from email_config import EmailConfig

logger = logging.getLogger(__name__)


class EmailService:
    """
    Service class for sending production reports via Gmail SMTP.

    Handles:
        - Connecting and authenticating to Gmail SMTP
        - Building HTML email bodies
        - Attaching CSV and PDF files
        - Sending to one or multiple recipients

    Usage:
        config        = EmailConfig.from_env()
        email_service = EmailService(config)
        email_service.send_daily_report(...)
    """

    def __init__(self, config: EmailConfig):
        self.config = config
        self.config.validate()

    # ── Private helpers ───────────────────────────────────────────────────────

    def _connect(self) -> smtplib.SMTP:
        """Create and return an authenticated Gmail SMTP connection."""
        server = smtplib.SMTP(self.config.smtp_host, self.config.smtp_port)
        server.ehlo()
        server.starttls()
        server.login(self.config.email, self.config.password)
        logger.info("SMTP connected to %s", self.config.smtp_host)
        return server

    def _attach_file(
        self,
        msg:        MIMEMultipart,
        file_bytes: bytes,
        filename:   str,
        mime_type:  str,
    ):
        """Attach a file to the email message."""
        part = MIMEBase("application", "octet-stream")
        part.set_payload(file_bytes)
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f'attachment; filename="{filename}"',
        )
        part.add_header("Content-Type", mime_type)
        msg.attach(part)

    def _build_daily_html(
        self, date_str: str, asset: str, total_records: int
    ) -> str:
        """Build the HTML body for the daily report email."""
        return f"""
        <html><body style="font-family: Arial, sans-serif; color: #333;">
          <div style="max-width:600px; margin:0 auto; border:1px solid #ddd;
                      border-radius:8px; overflow:hidden;">

            <div style="background:#1a3c5e; padding:24px; text-align:center;">
              <h1 style="color:#ffd700; margin:0; font-size:22px;">
                Daily Production Report
              </h1>
              <p style="color:#c8d8e8; margin:8px 0 0; font-size:14px;">
                {date_str}
              </p>
            </div>

            <div style="padding:24px;">
              <p style="font-size:14px; color:#555; line-height:1.8;">
                Dear Team,
              </p>
              <p style="font-size:14px; color:#555; line-height:1.8;">
                Please find attached the daily production report for
                <strong>{date_str}</strong> — Asset: <strong>{asset or 'All Assets'}</strong>.
                The report is available in both <strong>CSV</strong> (for Excel)
                and <strong>PDF</strong> formats.
              </p>

              <table style="width:100%; border-collapse:collapse; margin:20px 0;">
                <tr style="background:#f5f7fa;">
                  <td style="padding:10px 14px; font-size:13px; color:#666; width:40%;">Date</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{date_str}</td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; font-size:13px; color:#666;">Asset</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{asset or 'All Assets'}</td>
                </tr>
                <tr style="background:#f5f7fa;">
                  <td style="padding:10px 14px; font-size:13px; color:#666;">Total Records</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{total_records}</td>
                </tr>
              </table>

              <div style="background:#e8f0fe; border-left:4px solid #1a3c5e;
                          padding:12px 16px; border-radius:0 6px 6px 0;">
                <p style="margin:0; font-size:12px; color:#1a3c5e;">
                  This is an automated report generated by the Production
                  Automation System at 10:00 PM. Please do not reply to this email.
                </p>
              </div>
            </div>

            <div style="background:#f5f7fa; padding:12px; text-align:center;
                        border-top:1px solid #eee;">
              <p style="margin:0; font-size:11px; color:#999;">
                Production Automation System &nbsp;|&nbsp; Daily Report — 10:00 PM
              </p>
            </div>
          </div>
        </body></html>
        """

    def _build_monthly_html(
        self, year: int, month: int, asset: str, total_records: int
    ) -> str:
        """Build the HTML body for the monthly report email."""
        month_name = calendar.month_name[month]
        days       = calendar.monthrange(year, month)[1]
        return f"""
        <html><body style="font-family: Arial, sans-serif; color: #333;">
          <div style="max-width:600px; margin:0 auto; border:1px solid #ddd;
                      border-radius:8px; overflow:hidden;">

            <div style="background:#1a3c5e; padding:24px; text-align:center;">
              <h1 style="color:#ffd700; margin:0; font-size:22px;">
                Monthly Production Report
              </h1>
              <p style="color:#c8d8e8; margin:8px 0 0; font-size:14px;">
                {month_name} {year} — End of Month Summary
              </p>
            </div>

            <div style="padding:24px;">
              <p style="font-size:14px; color:#555; line-height:1.8;">
                Dear Team,
              </p>
              <p style="font-size:14px; color:#555; line-height:1.8;">
                Please find attached the monthly production summary for
                <strong>{month_name} {year}</strong> —
                Asset: <strong>{asset or 'All Assets'}</strong>.
                The report covers all {days} days of the month and is available
                in both <strong>CSV</strong> and <strong>PDF</strong> formats.
              </p>

              <table style="width:100%; border-collapse:collapse; margin:20px 0;">
                <tr style="background:#f5f7fa;">
                  <td style="padding:10px 14px; font-size:13px; color:#666; width:40%;">Month</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{month_name} {year}</td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; font-size:13px; color:#666;">Asset</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{asset or 'All Assets'}</td>
                </tr>
                <tr style="background:#f5f7fa;">
                  <td style="padding:10px 14px; font-size:13px; color:#666;">Total Records</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{total_records}</td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; font-size:13px; color:#666;">Days in Month</td>
                  <td style="padding:10px 14px; font-size:13px; font-weight:bold;">{days} days</td>
                </tr>
              </table>

              <div style="background:#e8f0fe; border-left:4px solid #1a3c5e;
                          padding:12px 16px; border-radius:0 6px 6px 0;">
                <p style="margin:0; font-size:12px; color:#1a3c5e;">
                  This is an automated end-of-month report generated by the
                  Production Automation System. Please do not reply to this email.
                </p>
              </div>
            </div>

            <div style="background:#f5f7fa; padding:12px; text-align:center;
                        border-top:1px solid #eee;">
              <p style="margin:0; font-size:11px; color:#999;">
                Production Automation System &nbsp;|&nbsp; Monthly Report — End of Month
              </p>
            </div>
          </div>
        </body></html>
        """

    # ── Public methods ────────────────────────────────────────────────────────

    def send_email(
        self,
        subject:     str,
        html_body:   str,
        attachments: List[Tuple[bytes, str, str]],
    ):
        """
        Send an email with attachments.

        Args:
            subject:     Email subject line.
            html_body:   HTML content of the email body.
            attachments: List of (file_bytes, filename, mime_type) tuples.
        """
        msg            = MIMEMultipart("mixed")
        msg["From"]    = self.config.email
        msg["To"]      = ", ".join(self.config.recipients)
        msg["Subject"] = subject

        msg.attach(MIMEText(html_body, "html"))

        for file_bytes, filename, mime_type in attachments:
            self._attach_file(msg, file_bytes, filename, mime_type)

        try:
            server = self._connect()
            server.sendmail(
                self.config.email,
                self.config.recipients,
                msg.as_string(),
            )
            server.quit()
            logger.info("Email sent | subject='%s' to=%s",
                        subject, self.config.recipients)
            print(f"✅ Email sent: {subject}")

        except Exception as e:
            logger.error("Failed to send email: %s", e)
            print(f"❌ Email failed: {e}")
            raise

    def send_daily_report(
        self,
        csv_bytes:     bytes,
        csv_filename:  str,
        pdf_bytes:     bytes,
        pdf_filename:  str,
        date_str:      str,
        asset:         str = None,
        total_records: int = 0,
    ):
        """Send the daily production report with CSV and PDF attached."""
        subject   = f"Daily Production Report — {date_str} | {asset or 'All Assets'}"
        html_body = self._build_daily_html(date_str, asset, total_records)

        self.send_email(
            subject=subject,
            html_body=html_body,
            attachments=[
                (csv_bytes, csv_filename, "text/csv"),
                (pdf_bytes, pdf_filename, "application/pdf"),
            ],
        )

    def send_monthly_report(
        self,
        csv_bytes:     bytes,
        csv_filename:  str,
        pdf_bytes:     bytes,
        pdf_filename:  str,
        year:          int,
        month:         int,
        asset:         str = None,
        total_records: int = 0,
    ):
        """Send the monthly production report with CSV and PDF attached."""
        month_name = calendar.month_name[month]
        subject    = f"Monthly Production Report — {month_name} {year} | {asset or 'All Assets'}"
        html_body  = self._build_monthly_html(year, month, asset, total_records)

        self.send_email(
            subject=subject,
            html_body=html_body,
            attachments=[
                (csv_bytes, csv_filename, "text/csv"),
                (pdf_bytes, pdf_filename, "application/pdf"),
            ],
        )